# Generated by Django 3.2.7 on 2021-09-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_app', '0001_initial'),
        ('machine_app', '0002_auto_20210907_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.image')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_app.machine')),
            ],
        ),
    ]
