# Generated by Django 3.2.7 on 2021-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20210924_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='project',
            name='g_code',
            field=models.TextField(default=''),
        ),
    ]
