# Generated by Django 3.2.7 on 2021-10-11 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0003_auto_20210924_1052'),
        ('machine_app', '0004_auto_20210922_1302'),
        ('image_app', '0002_auto_20210922_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_app.image')),
                ('machines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_app.machine')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.project')),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_app.tool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
