# Generated by Django 3.2.7 on 2021-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_app', '0002_auto_20210907_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='color',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
