# Generated by Django 3.2.7 on 2021-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_app', '0003_tool_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='x_min_range',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='y_min_range',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='z_min_range',
            field=models.FloatField(default=0),
        ),
    ]
